---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yangsuite
  namespace: yangsuite
  labels:
    app.kubernetes.io/name: yangsuite
    app.kubernetes.io/instance: yangsuite
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: yangsuite
      app.kubernetes.io/instance: yangsuite
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yangsuite
        app.kubernetes.io/instance: yangsuite
    spec:
      securityContext:
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: yangsuite-init
          tty: true
          image: ghcr.io/sirtux/yangsuite:{{ .Values.yangsuite.version }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 999
            runAsUser: 999
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "yangsuite.{{ .Values.cluster | replace "cluster-" "" }}.wirkbetrieb.net"
            - name: YANGSUITE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yangsuite-db-app
                  key: password
            - name: YANGSUITE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: yangsuite-db-app
                  key: host
          volumeMounts:
            - name: "yangsuite-static"
              mountPath: "/opt/yangsuite/.local/share/yangsuite/static"
          command:
            - yangsuite
            - -c
      containers:
        - name: yangsuite
          tty: true
          image: ghcr.io/sirtux/yangsuite:{{ .Values.yangsuite.version }}
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 999
            runAsUser: 999
          env:
            - name: DJANGO_ALLOWED_HOSTS
              value: "yangsuite.{{ .Values.cluster | replace "cluster-" "" }}.wirkbetrieb.net"
            - name: YANGSUITE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yangsuite-db-app
                  key: password
            - name: YANGSUITE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: yangsuite-db-app
                  key: host
          volumeMounts:
            - name: "yangsuite-static"
              mountPath: "/opt/yangsuite/.local/share/yangsuite/static"
          command:
            - uwsgi
            - /opt/yangsuite/uwsgi.ini
          ports:
            - name: "http"
              containerPort: 8080
      volumes:
        - name: "yangsuite-static"
          emptyDir: {}